AtB-AS/webshop

src/elm/Page/History.elm, src/static/styles/main.scss
Initial version of this functionality. Depending on the design, might need to ask the user for their email address. For now, uses the one in the profile if one is defined.
Fixes #31
=> Add support for getting receipts

webpack.config.js
This also formats file according to #33.
=> fix: Adds better error message on missing local config

package.json, src/elm/Fragment/Icon.elm, src/elm/Main.elm, src/elm/Page/Shop.elm, src/elm/Ui/Message.elm, src/elm/Ui/Section.elm, src/static/styles/main.scss, src/static/styles/ui.scss, yarn.lock
~_This is kind of dirty PR, I apologize. My elm format doesn't seem to match yours @mjenssen making the changeset bigger and harder to follow._~
This PR introduces UI module with components for section box and status message and starts a system for making reusable components. Currently just used in order summary.
=> feat: adds separate UI component module using @atb-as/theme

src/static/styles/ui.scss
Fikser rapportert feil fra @magnusolderoesaether
=> fix: radio inputs were visible in Safari

.github/workflows/deploy-prod.yml, .github/workflows/deploy-staging.yml, README.md, src/static/index.js, webpack.config.js
Note that the Firebase config is no longer embedded in the code.
=> Add workflow for deploying to production on tag

.firebaserc, .github/workflows/deploy-preview.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-staging.yml, firebase.json
This makes is possible to refer to the same target name but different application names in Firebase.
=> Use target feature of Firebase Hosting

src/static/index.js
=> Refresh JWT token from Firebase when it nears expiration

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature.md
Forslag til templates med innebygget akseptansekriterier for features. Kan også legge til akseptansekriterier for bugs.
=> chore: Adds templates for feature and bug

src/elm/Page/Account.elm, src/static/styles/ui.scss
Fikser påpekte feil som rapportert av @tormoseng i https://github.com/AtB-AS/webshop/issues/19#issuecomment-827638486.
=> fixes: reports after QA

src/elm/Page/Login.elm, src/static/styles/ui.scss
Gjør slik at inputs ikke får rar farge ved autoutfylling. Også at engangspassord ikke får autocomplete, da det ikke gir mening.
=> fix: autofill and autofill color for inputs

src/static/index.html, src/static/index.js, src/static/styles/main.scss
Legger til Intercom for feedback
Fixes #79
=> feat: adds Intercom

src/static/styles/main.scss, src/static/styles/ui.scss
Fikser feil ved https://github.com/AtB-AS/webshop/issues/93#issuecomment-829940374
=> fix: Responsive headers

.gitignore, README.md, package.json, webpack.config.js, yarn.lock
This handles missing local file vs invalid local file better, and also adds support for .env file in the case of using environment variables.
=> Improve configuration of build environment

src/static/styles/ui.scss
=> fix: button icon for vipps

src/elm/Data/FareContract.elm, src/elm/Service/Misc.elm, src/static/index.js
Fikser feil hvor modellen av decoding av ukjente tickets er for streng.
=> fix: parsing issue of unknown tickets

src/elm/Page/Login.elm, src/elm/Ui/Input/Text.elm
Endrer til at innloggingsboks på mobil er mer brukervennlig.
=> feat: improves usability for phone code confirm input

src/elm/Main.elm, src/elm/Page/Overview.elm, src/elm/Service/Misc.elm, src/elm/Ui/Button.elm, src/elm/Ui/Group.elm, src/elm/Ui/Input/Radio.elm, src/elm/Ui/Input/Text.elm, src/elm/Ui/LabelItem.elm, src/elm/Ui/Section.elm, src/elm/Ui/TextContainer.elm, src/static/index.html, src/static/index.js, src/static/styles/main.scss, src/static/styles/ui.scss
Fikser opp i litt smårask som ugyldig HTML og noen rariteter med CSS bruk.
Skal i praksis fungere som før og vises som før, men uten noen rare feil som oppstår. Det er mange endringer i cross cutting components så det kan introdusere regresjonfeil. Burde kjøre igjennom litt strukturert QA.
Har gått igjennom løsningen, men ikke systematisk med skjermstørrelser og forskjellige nettlesere. Kan være det introduserer noen feil (eller retter opp i feil som var hacket rundt). Men jeg oppretter PR slik at flere eventuelt kan klikke seg igjennom.
=> fix: fixes different CSS issues and render bugs, validating HTML

src/elm/Page/Login.elm
Oppdaterer tekst som vises i toppen av login-boks.
=> fix: updates login text

src/elm/Page/Account.elm, src/elm/Page/Overview.elm, src/elm/Ui/TravelCardText.elm, src/elm/Util/TravelCard.elm, src/static/styles/ui.scss
=> feat: formats phone number and travel card number in overview page

src/static/styles/main.scss
=> feat: reduces padding on smaller devices

src/elm/Data/RefData.elm, src/elm/Page/Shop.elm, src/elm/Service/RefData.elm, src/elm/Shared.elm
Ref samtale med @magnusolderoesaether og @vidtil . Enkeltbilletter i webshop er visst ikke helt kartlagt og håndtert enda. Det kan og være noen tekniske utfordringer her. Unnlater å vise for nå.
Burde det her også gjøres noe i backend for å ikke tillatte web som distribution channel for enkeltbilletter, @mjenssen ?
=> fix: hide single tickets from shop in webshop

src/elm/Page/Account.elm
=> fix: change email icon from trash can to pen

src/elm/Page/Account.elm, src/elm/Ui/Button.elm, src/static/styles/main.scss, src/static/styles/ui.scss
=> feat: adds delete link to email

src/elm/Page/Overview.elm
=> fix: improves copy for top notice on ticketing overview

src/elm/Page/Account.elm
Oppdaterer tekst etter dialog med kundeservice.
=> fix: adds notice on ID for delete email text

src/elm/Page/Account.elm, src/elm/Page/History.elm, src/elm/Page/Login.elm, src/elm/Page/Onboarding.elm, src/elm/Page/Shop.elm, src/elm/Ui/Input/Select.elm, src/static/styles/main.scss, src/static/styles/ui.scss
Samle PR for QA-funn. WIP
- Fikser outline for primary button til å ikke være samme farge som knappen
- Setter (åpner ny side) på alle lenker med target _blank
- Forbedrer UU for sonevelger (rett bruk av label)
- Små forbedringer for skjermleser ved kjøp av billetter
- Fjerner ufungerende filter fra billetthistorikk
=> fix: Quick fixes after QA

.github/ISSUE_TEMPLATE/feature.md, src/elm/GlobalActions.elm, src/elm/Main.elm, src/elm/Page/Account.elm, src/elm/Page/History.elm, src/elm/Page/Overview.elm, src/elm/Page/Shop.elm, src/elm/Util/PageTitle.elm, src/static/index.html, src/static/index.js, src/static/manifest.json
=> feat: set page title for each sub page

src/elm/Page/Account.elm, src/elm/Page/Onboarding.elm, src/elm/Util/TravelCard.elm
Ses i sammenheng med https://github.com/AtB-AS/webshop-backend/pull/11. https://github.com/AtB-AS/webshop-backend/pull/11 må merges før denne
=> fix: pass inn full travel card to store on profile

src/static/styles/ui.scss
https://github.com/AtB-AS/webshop/issues/17#issuecomment-860634790
=> fix: adds focus outline for checkboxe component

src/elm/Data/Webshop.elm, src/elm/Main.elm, src/elm/Page/Account.elm, src/elm/Page/Onboarding.elm, src/elm/Service/Webshop.elm, src/elm/Util/Maybe.elm, src/static/styles/ui.scss
=> Add editing of consents to profile page

src/elm/Page/Login.elm
=> fix: fix autocomplete for password in login

src/elm/Page/Account.elm
See https://mittatb.slack.com/archives/C01MT34KJ4B/p1624455065218100
=> fix: remove text on using mobile as tickets

src/elm/Page/Shop/Carnet.elm, src/elm/Page/Shop/CommonViews.elm, src/elm/Page/Shop/Period.elm, src/elm/Page/Shop/Summary.elm, src/elm/Page/Shop/Utils.elm, src/elm/Ui/AccessibleFieldset.elm, src/static/styles/ui.scss
=> feat: adds zones to summary and always expanded

src/elm/Page/Onboarding.elm
Ref https://mittatb.slack.com/archives/C01MT34KJ4B/p1624624851271500?thread_ts=1624624395.270700&cid=C01MT34KJ4B
=> fix: deactivate app advert for now

src/static/styles/ui.scss
Fikser https://github.com/AtB-AS/webshop/issues/159#issuecomment-869409471
=> fix: option colors on Edge

src/static/index.js
Fixes #258
La til install id og commit id.
Kan velge å legge til Firebase Auth Id og, men usikker på om den er sensitiv eller ikke i denne settingen. Kanskje @cbrevik vet?
=> feat: adds install id and build number to intercom. fixes #258

firebase.json
Legger på noen enkle CSP/xss headers.
=> feat: adds security headers to firebase

src/elm/Page/Login.elm
=> fix: adds link to read more on initial read screen

.github/release-drafter.yml
Legger til seperat config slik at #280 kan testes før merge.
=> chore: adds release drafter config

.github/workflows/deploy-preview.yml
Reduserer sjansene for å gå ut over quotas. Kan være det kan være noe lengre, men antar at det kanskje blir fornya på new deploy. Vet du noe der @mjenssen ?
=> chore: Reduserer levetid til preview deploys

src/elm/Page/Login.elm
Feilmeldinger fra Firebase vises ikke ved innlogging av telefon nå. Dette fikser det.
=> fix: Fikser manglende visning av feilmelding for innlogging via telefon.

src/static/styles/main.scss
Litt padding feil i header på små skjermer nå
=> fix: Avstand på logo på små skjermer

src/static/index.js
=> fix: Oversetter feilmelding ved feil passord

src/elm/Page/Shop/Summary.elm
=> feat: Legger til info om mulig ugyldig billett i metrobuss

src/elm/Main.elm, src/elm/Ui/HamburgerButton.elm, src/static/index.js, src/static/navigation.js, src/static/styles/main.scss, src/static/styles/ui.scss
Legger til alles favorittburger.
=> feat: Legger til navigasjon for små enheter

src/elm/Main.elm, src/static/navigation.js
=> fix: UU feil i hamburgermeny

src/elm/Page/Onboarding.elm
Fixes #156 
Legger til autofokus for t:kort input på onboarding. Vil også gjøre input mer tydelig
=> feat: adds auto focus to travel card input on onboarding

src/elm/Page/Account.elm
=> fix: adds ability to remove email in Account page. fixes #138

src/elm/Main.elm, src/elm/Page/Overview.elm, src/elm/Ui/TicketDetails.elm
=> Add option to request receipt from detailed view of ticket

src/elm/Main.elm, src/elm/Page/Overview.elm, src/elm/Page/Shop/CommonViews.elm, src/elm/Page/Shop/Period.elm, src/elm/Service/Misc.elm, src/elm/Ui/TicketDetails.elm, src/static/index.js
=> Add validation for date selection in shop

src/elm/Page/Shop/Carnet.elm, src/elm/Page/Shop/CommonViews.elm, src/elm/Page/Shop/Period.elm, src/elm/Page/Shop/Utils.elm
=> Add warning when user tries to purchase overlapping tickets

src/elm/Util/FareContract.elm
=> Filter out refunded tickets in overview page

src/elm/Data/Ticket.elm, src/elm/Page/Shop/Carnet.elm, src/elm/Page/Shop/CommonViews.elm, src/elm/Page/Shop/Period.elm, src/elm/Page/Shop/Summary.elm, src/elm/Page/Shop/Utils.elm, src/elm/Service/Ticket.elm
=> Add valid to in summary

src/elm/Page/Shop/Period.elm, src/elm/Util/FareContract.elm
=> Don't show warning for overlapping tickets with a refunded ticket

src/elm/Page/Shop/Carnet.elm, src/elm/Page/Shop/Period.elm
=> Fix resetting overlap message

src/elm/Page/History.elm, src/elm/Page/Shop/Carnet.elm, src/elm/Page/Shop/CommonViews.elm, src/elm/Page/Shop/Period.elm, src/elm/Page/Shop/Summary.elm, src/elm/Ui/Input/Select.elm, src/static/styles/ui.scss
=> Prepare limited carnet rollout

e2e-tests/cypress.json, e2e-tests/cypress/integration/pageobjects/buyticket.pageobject.js, e2e-tests/cypress/integration/pageobjects/myprofile.pageobject.js, e2e-tests/cypress/integration/pageobjects/mytickets.pageobject.js, e2e-tests/cypress/integration/tests/a11y.e2e_spec.js, e2e-tests/cypress/integration/tests/carnettickets.e2e_spec.js, e2e-tests/cypress/integration/tests/missing_travelCard_spec.e2e.js, e2e-tests/cypress/integration/tests/mytickets.e2e_spec.js, e2e-tests/cypress/integration/tests/periodtickets.e2e_spec.js, e2e-tests/cypress/integration/tests/x_onboarding.e2e_spec.js, e2e-tests/cypress/plugins/index.js, e2e-tests/cypress/support/commands.js
* periodtickets.e2e_spec.js: tester operasjoner for å kjøpe periodebillett
* carnettickets.e2e_spec.js: tester operasjoner for å kjøpe klippekort
* missing_travelCard_spec.e2e.js: lagt testscenario for manglende t:kort til en egen bruker for å unngå mange operasjoner på t:kort (og dermed minske kjøretid)
=> e2e-tester av billettkjøpssidene

e2e-tests/cypress/integration/pageobjects/common.pageobject.js, e2e-tests/cypress/integration/pageobjects/history.pageobject.js
To små rettinger. Bl.a. for #335
=> small-e2e-fixes

e2e-tests/cypress.json, e2e-tests/cypress/integration/pageobjects/buyticket.pageobject.js, e2e-tests/cypress/integration/pageobjects/myprofile.pageobject.js, e2e-tests/cypress/integration/pageobjects/onboarding.pageobject.js, e2e-tests/cypress/integration/tests/a11y.e2e_spec.js, e2e-tests/cypress/integration/tests/carnettickets.e2e_spec.js, e2e-tests/cypress/integration/tests/missing_storedInformation.e2e_spec.js, e2e-tests/cypress/integration/tests/myprofile.e2e_spec.js, e2e-tests/cypress/integration/tests/mytickets.e2e_spec.js, e2e-tests/cypress/integration/tests/periodtickets.e2e_spec.js, e2e-tests/cypress/integration/tests/x_onboarding.e2e_spec.js, e2e-tests/cypress/support/commands.js
* lagt til tester for ny consent
* lagt til tester for lagring av betalingskort
* oppdatert fremtidig billett som det sjekkes på
* feil-fixer
=> e2e-updates

src/elm/Environment.elm, src/elm/Main.elm, src/elm/Service/RefData.elm, src/elm/Service/Ticket.elm, src/static/index.js, webpack.config.js
Also removed the elm flags refDataUrl and ticketUrl. RefDataUrl was no longer used, and ticketUrl was the same as base url.
=> feat: Decode flags when starting webshop

.github/workflows/e2e-tests-edge.yml, .github/workflows/e2e-tests-firefox.yml, .github/workflows/e2e-tests.yml, e2e-tests/cypress/integration/pageobjects/buyticket.pageobject.js, e2e-tests/cypress/integration/pageobjects/myprofile.pageobject.js, e2e-tests/cypress/integration/tests/a11y.e2e_spec.js, e2e-tests/cypress/integration/tests/carnettickets.e2e_spec.js, e2e-tests/cypress/integration/tests/missing_storedInformation.e2e_spec.js, e2e-tests/cypress/integration/tests/mytickets.e2e_spec.js, e2e-tests/cypress/integration/tests/periodtickets.e2e_spec.js, e2e-tests/cypress/integration/tests/x_onboarding.e2e_spec.js, e2e-tests/package.json, e2e-tests/yarn.lock
- Opprettet yml-filer for å kjøre e2e-testene på firefox (gjennom ubuntu-latest og Docker) og edge (windows-latest)
- Endret std yml til å kjøre Chrome
- Tatt inn endringer fra betalingslagring og uu-fixer
=> [e2e-tests] kjør tester på firefox og edge

e2e-tests/cypress/integration/pageobjects/history.pageobject.js, e2e-tests/cypress/integration/tests/history.e2e_spec.js, e2e-tests/cypress/integration/tests/myprofile.e2e_spec.js, e2e-tests/cypress/integration/tests/mytickets.e2e_spec.js
- also updated the travel card number due to an error
=> e2e-test: multiple products on an order

package.json
Legger til mulighet for å bruke samme miljøvariabel som prosjektet til å spesifisere hvilket prosjekt som skal settes opp. Det for å bedre kunne støtte forskjellige miljøer fra GH actions.
=> feat: adds ability to use arbitrary org when building

orgs/atb.json, orgs/nfk.json, src/elm/Base.elm, src/elm/Data/Organization.elm, src/elm/Main.elm, src/elm/Page/Account.elm, src/elm/Page/Onboarding.elm, src/elm/Util/Validation.elm
Endrer slik at hjelpen med gyldig prefix for t:kortid er konfigurerbart på org nivå.
=> feat: adds configurable travelcard valid prefix validation to support several orgs

src/elm/Page/Shop/Carnet.elm, src/elm/Page/Shop/Period.elm, src/elm/Page/Shop/Summary.elm
=> feat: updates tkort warning text and reuse component

orgs/nfk.json
Dette i en testperiode for å hindre blokkering.
=> feat: deactivate travelcard number validation for NFK

package.json, yarn.lock
Dette skal ikke være en endring som endrer noe særlig. NFK vil få nye farger men AtB skal fungere som før.
=> chore: updates @atb-as/theme dep to latest

e2e-tests/cypress/integration/tests/carnettickets.e2e_spec.js, e2e-tests/cypress/integration/tests/myprofile.e2e_spec.js, e2e-tests/cypress/integration/tests/periodtickets.e2e_spec.js, src/elm/Fragment/Icon.elm
Fikser som rapportert https://github.com/AtB-AS/webshop/pull/426#issuecomment-981594110
=> fix: visa/mastercard icons after asset changes

src/static/styles/ui.scss
=> fix: ticket illustration pixel gap

e2e-tests/cypress.json, e2e-tests/cypress/integration/tests/a11y.e2e_spec.js, e2e-tests/cypress/integration/tests/missing_storedInformation.e2e_spec.js, e2e-tests/cypress/integration/tests/myprofile.e2e_spec.js, e2e-tests/cypress/integration/tests/mytickets.e2e_spec.js, e2e-tests/cypress/integration/tests/x_onboarding.e2e_spec.js, e2e-tests/cypress/support/commands.js
- Updates on Firebase requests from https://github.com/AtB-AS/webshop/pull/452
- Added check if config is loaded from Firestore before continuing
- Remove SRI-hashes for Cypress with "experimentalSourceRewriting" (ref https://github.com/cypress-io/cypress/issues/2393)
- Remove comments related to fixed bugs
- Include extra check on onboarding after fix on "Next" vs "Skip"
- Remove error-check on editing phone numers as this is fixed
=> E2E updates after Firebase changes

e2e-tests/cypress/integration/tests/a11y.e2e_spec.js, e2e-tests/cypress/integration/tests/carnettickets.e2e_spec.js, e2e-tests/cypress/integration/tests/periodtickets.e2e_spec.js
Oppdaterte testene etter prisendringer.
=> e2e-test-fix etter prisendringer

package.json, yarn.lock
Skal fikse bilde til NFK hvor det var noen føtter som ikke burde vises.
Påvirker ikke AtB
=> chore: bumps design system (fixing login illustration)

src/elm/Page/Shop/Summary.elm
Fikser https://github.com/AtB-AS/webshop/pull/476#discussion_r806654928
=> fix: summary three column issue

src/elm/Service/Ticket.elm
=> fix: sca_exemption typo

README.md
Update test description for production verification
=> fix: Update test descriptions in README.md

e2e-tests/cypress/integration/tests/myprofile.e2e_spec.js, e2e-tests/cypress/integration/tests/mytickets.e2e_spec.js
Fikk på en eller annen måte ikke fikset alle e2e-feil ved forrige fix-commit. Denne skal forhåpentligvis fikse de siste problemene.
=> test: more e2e test fixes
