.github/workflows/deploy-preview.yml
.github/workflows/deploy-staging.yml
README.md
webpack.config.js

The preview channel is for creating a temporary deployment for each pull request that lives for 30 days.  Staging is for the permanent staging deployment.
Production deployments are not added yet as the backend isn't deployed and configurations are missing in the production environment.
Not sure how to test this properly, but all non-code configuration seems to be in order now.

Add initial GitHub Actions for preview and staging

---

.github/workflows/deploy-preview.yml
.github/workflows/deploy-staging.yml

Dette vil ganske drastisk forbedre byggetid som er litt viktig når vi har kontinuerlig previews her slik at det er enklere å dele lenker med en gang.

fix: adds cache to gh actions to reduce yarn install time

---

src/elm/Data/RefData.elm
src/elm/Main.elm
src/elm/Notification.elm
src/elm/Page/Shop.elm
src/elm/Service/RefData.elm
src/elm/Shared.elm
src/elm/Util/Func.elm

Litt knot dette. Men i FareContracts i RemoteConfig så ligger det en oversikt over hvilke UserTypes som er gjeldene for hver. Her lager jeg en liste med gyldige begrensninger og lager en mappen fra og tilbake fra produkter. For at dette skal være mest naturlig endrer jeg også rekkefølge på billettype.
Men det kan være tilfeller hvor man velger F.eks Enkeltbillett, så Ungdom og deretter Periode-billett. I disse tilfellene resetter jeg bare tilstand til å ha voksen som valgt kategori. Kan være vi på et tidspunkt skal heller legge inn en validering eller noe, da det kan være litt misvisende og overraskende.

fix: only show fare products of right type

---

src/elm/Ui/Input/Radio.elm

Fikser feil som sett på bildet:

fix: missing new line for radio buttons

---

src/static/index.js

Fikser feil hvor det kommer feilmelding ved normal utlogging. Denne feilmeldingen burde kun dukke opp når det er en feil hvor loggedIn i localStorage er aktiv selv om firebase sier noe annet (for å unngå tidligere evig loading screen).

fix: dont show error when logging out normally

---

src/static/styles/ui.scss

Endrer input (text og radio) til nytt design med ikke border-radius for elementer som er "mid-section".

fix: border radius for radio inputs

---

src/elm/Page/History.elm
src/static/styles/main.scss
src/static/styles/ui.scss

Fixes #109
Skriver om history-visning til å være noe mer universelt utformet og responsive ved å bruke gjenbrukbare UI components. Legger også til warning-boks ved manglende epost for å gjøre det litt mer forståelig. Dette i påvente av full implementasjon av bedre flyt for sending av epost.

feat: adds warning on missing email for receipt

---

src/static/styles/main.scss
src/static/styles/ui.scss

Safari har mer padding/margin på enkelte elementer enn andre nettlesere. Fremfor å kompensere for det på hvert element er det greit å nullstille ("normalize") for alle elementer. Dette burde ikke få store konsekvenser utenfor andre nettlesere men kan introdusere noe småfeil som jeg ikke fant etter gjennomgang her.
Fjerner også border-radius på fokus på punkter som en del av feil som ser litt rart ut i Safari som uansett skulle fikses opp i som en del av design sync på et tidspunkt.

fix: render issues with Safari

---

README.md
firebase.json
src/elm/Environment.elm
src/elm/Main.elm
src/elm/Page/Shop.elm
src/elm/Route.elm
src/elm/Service/Misc.elm
src/elm/Service/Ticket.elm
src/static/index.js
src/static/styles/main.scss

Dette legger til en enkel (midlertidig) side for mottak av betaling via Vipps. Dette for å gi noe mer kontekst etter endt betaling eller avbrutt betaling i Vipps. Dette er ikke optimalt, men for at det skal være litt bedre trengs det mye mer omskriving og noen kode-konseptuelle endringer. Se #107 og #105 for kontekst.
For å få til dette må det gjøres om til å ikke bruke skigard-tegn i URL. Men det er uansett en fordel og modernisering av gammel måte å håndtere "SPA routing" på. 
TODO:
Trenger copy på meldinger. Helt konkret melding som kommer opp som boks når man har fått kjøpt billett.

feat: adds "thanks" page as redirect target after Vipps payment

---

src/static/styles/ui.scss

Unngår bevegelse i elementet ved lasting av side eller nye elementer. Kun gjør overganganimasjon på border.

fix: transition for input texts

---

src/static/styles/ui.scss

Det ble gjort en feil med håndtering av størrelser for labeling ved å sette section item til grid for å kompensere for størrelseshåndtering av input som barn i Safari. En bedre løsning er å faktisk definere label som block slik som var tiltenkt egentlig.

fix: proper handling of label sizing as child of section

---

src/elm/Data/RemoteConfig.elm
src/elm/Page/Shop.elm
src/elm/Service/RemoteConfig.elm
src/elm/Shared.elm
src/elm/Ui/LabelItem.elm
src/elm/Ui/LoadingText.elm
src/elm/Ui/Section.elm
src/static/index.js
src/static/styles/main.scss
src/static/styles/ui.scss

Fixes #20
Legger til MVA og gyldig fra i oppsummeringen. Ingen enkel måte å hente ut `gyldig til` akkurat nå. Så vi må eventuelt finne ut en måte å kalkulere det på på et vis.
Legger også opp til å kunne hente ut mer info fra RemoteConfig (som feature toggles etterhvert).

feat: adds validity to buy ticket summary

---

.github/workflows/deploy-prod.yml
README.md
src/static/index.html
webpack.config.js

Dette er ikke en fullverdig løsning, men det gir oss noe å gå på. Ettersom det er mye klientside navigasjon så er det ikke alle ting som fanges opp her. Må på et tidspunkt utvide dette til å ha en Elm-bibliotek som lar oss trigge events fra forskjellige effekter (klikk, navigasjon, etc).
Men akkurat nå får vi i alle fall noe statistikk inn i samme kanal som øvrige ting. Noe av dette finnes nok sikkert via Firebase også.

feat: adds initial naive google analytics

---

src/elm/Data/Ticket.elm
src/elm/GlobalActions.elm
src/elm/Main.elm
src/elm/Page/Overview.elm
src/elm/Page/Shop.elm
src/elm/Route.elm
src/elm/Service/Misc.elm
src/elm/Service/Ticket.elm
src/elm/Ui/TicketDetails.elm
src/elm/Util/PhoneNumber.elm
src/static/index.js

Skriver om kjøpsflyten til å være i samme vindu og håndtere flere caser. Gjort noen endringer i tilstandshåndtering for kjøpsvinduet. Det gjør det mer stabilt og åpner for å refreshe siden. Men når man refresher, eller navigerer tilbake fra kjøpsvindu (vipps/nets) så er state resatt. For å løse det må vi til med noe ala localstorage eller på selve brukeren med reserverte kjøp. Men det blir ikke i scope for denne oppgaven.
- Lagre i local state (localstorage) ved reservation i kjøpsskjerm for når det sendes tilbake med feil eller navigerer tilbake til siden så huskes det aktive kjøpet uten å måtte gjøre det på nytt.
Fixes #107

feat: Improves purchase flow for better a11y and robustness 

---

src/elm/Page/History.elm
src/elm/Page/Login.elm
src/elm/Page/Shop.elm
src/elm/Ui/Message.elm

Se kommentar om ny flyt i #152. Her gjør vi det enkelt med å ha egen informasjonsside på AtBeta og lenker til den fra innloggingen. Se også https://github.com/AtB-AS/atbeta/pull/39
Fixes #152

Legger til informasjon under innlogging som peker til onboardings info

---

src/elm/Page/History.elm

Gjør det veldig enkelt her, bare viser refundert når den er det. Hele denne siden burde revitaliseres litt med design og implementasjon. Se #129
Fixes #131

fix: show refunded on refunded orders

---

src/elm/Fragment/Icon.elm
src/elm/Main.elm
src/elm/Page/Shop.elm
src/elm/Page/Shop/Carnet.elm
src/elm/Page/Shop/Common.elm
src/elm/Page/Shop/CommonViews.elm
src/elm/Page/Shop/Period.elm
src/elm/Page/Shop/Summary.elm
src/elm/Page/Shop/Utils.elm
src/elm/Page/ShopCarnet.elm
src/elm/Ui/Group.elm
src/elm/Ui/Input/Radio.elm
src/elm/Ui/PageHeader.elm
src/static/styles/main.scss
src/static/styles/ui.scss

Legger til en egen subside for oppsummering. Dette ligger ikke under egen route per nå, men det kan vi vurdere om er hensiktsmessig etterhvert.
Skriver også om til å ha en egen Shop-struktur for pages som gjenbruker logiske funksjoner og views der hensiktsmessig.
Her viser vi ikke "gyldig til". Se egen sak: https://github.com/AtB-AS/atb-ticket/issues/62
TODO:
Skjermskudd:

feat: adds initial reusable summary subpage

---

src/elm/Page/Overview.elm

fix: only show travel card in overview if set

---

src/elm/Main.elm

Hindrer at melding om billett-validitet vises om du ikke er logget inn.

fix: only show validity warning when logged in

---

.github/workflows/draft.yml

Forslag om å legge til Release Drafter som GH Action. Den vil opprette en draft release og oppdatere den kontinuerlig med endringer. Slik synliggjør vi kommende endringer og det gjør arbeidet enklere for å release nye oppdateringer.
Usikker på om dette gjøres på Pull Request nivå (som jeg håper) eller om den ser på commits. Om det er på commits må vi alltid squashe og se på semantiske titler på merge. Om det er på pull requests er det enklere for da trenger vi bare opprette korrekt pullrequest tittel som vi ønsker skal dukke opp i changelog.

chore: adds release drafter gh action

---

firebase.json

Fjerner manuell CSP håndtering inntil vi kan finne en enklere måte å bruke strict CSP eller andre alternativer. Blir for mye allowlisting og fjas med Intercom, reCaptcha, Firebase, GA.

fix: removes manual CSP

---

src/elm/Page/Account.elm
src/elm/Page/Login.elm
src/elm/Page/Onboarding.elm
src/elm/Page/Shop/Summary.elm
src/elm/Util/PhoneNumber.elm
src/elm/Util/Validation.elm

Det var tidligere litt usikkerhet rundt utenlandske telefonnummer og bruk av de i nettbutikken. Entur støtter det med Vipps støtter det ikke. Dette er også slik det fungerer i dag men det er noe implisitt med standard landskode.
Dette prøver å gjøre det mer tydelig med å:
- Forhåndsutfylle landskode visuelt (+47).
- Legger på landskode om mangler (default +47)
- Viser advarsel rundt vipps i kjøpsflyt dersom du har ikke-NO telefonnummer.
Den fikser også at telefonnummer er valgfritt så man kan fjerne det i profil i ettertid.
Closes #254

feat: Små forbedringer til tydelighet for telefonnummer

---

src/static/index.js

Legger til flere forsøk på å hente ut gyldig token om det er noe feil med expiretime som blir returnert. Dette skal forhåpentligvis fikse utgått JWTs. 
Om refresh token er ugyldig så fanges det ikke opp. Dette kan skje med at bruker blir disabled/slettet eller endrer innloggingsinformasjon. Må verifisere hvordan det håndteres.

fix: reload page on expired jwt

---

src/elm/Ui/Message.elm
src/static/styles/ui.scss

Prøver meg på en endring her jeg ikke helt greier å stabilt skjønne konsekvensene av i forskjellige scenario. Vært fint å testet på forskjellige enheter i forskjellige bruksområder.
Her er en endring som setter alle meldinger (meldingsbokser) til en alert for skjermlesere. I praksis gjør det at den blir lest opp nå den dukker opp. Men jeg vet ikke om all vår bruk gjør at det blir korrekt. Så vært fint med test i voice over, talkback osv.

feat: adds role alert for all messages

---

src/elm/Ui/PageHeader.elm
src/elm/Ui/ProgressHeader.elm

Some heading text changes is not registered by screen readers as the
virtual dom does not change, only the text content. By using Html.Keyed
and using the text as the keyed value, the node will be replaced in the
dom, and the change registered by the screen reader.

feat: Add Html.Keyed to headings

---

src/elm/Data/PaymentType.elm
src/elm/Data/Ticket.elm
src/elm/Page/Shop/Carnet.elm
src/elm/Page/Shop/Period.elm
src/elm/Page/Shop/Summary.elm
src/elm/Service/RefData.elm
src/elm/Service/Ticket.elm
src/elm/Shared.elm
src/static/index.js

This adds support for MasterCard and American Express, and also makes the payment types configurable from Remote Config. This way we can easily add and remove payment types without deploying new code.
Closes #337

Add support for more payment types

---

src/elm/Page/Account.elm
src/elm/Page/History.elm
src/elm/Page/Onboarding.elm
src/elm/Page/Overview.elm
src/elm/Page/Shop/Carnet.elm
src/elm/Page/Shop/Period.elm
src/elm/Ui/Button.elm
src/elm/Ui/Message.elm
src/elm/Ui/PageHeader.elm
src/elm/Ui/ProgressHeader.elm
src/static/styles/ui.scss

When a user using a screen reader navigates the webshop, the heading
should be focused when changing page. This is more inline with the
guidelines for WGAT 2.0 2.4.3.
This was made possible by using the domFocus helper from Elm. The
focusable elements needs to have an id, and a tab-index too be
focusable. The tab-index is set to -1 to not be accessible during normal
tabbing.
Changed message-box aria-live to only be assertive when the status level
is Error or Warning. Also removed aria-live from buttons, which are no
longer assertive if disabled or loading.

feat: Focus headings after changing page

---

src/elm/Main.elm
src/elm/Page/History.elm
src/elm/Page/Login.elm
src/elm/Ui/Expandable.elm
src/elm/Ui/ScreenReaderText.elm
src/elm/Ui/TicketDetails.elm

Order ids were by some screen readers read as gibberish words. This
commit makes the order ids spellable by adding a comma between each
character.
Also fixes a bug where some screen readers did not register that a
expandable element was opened.

feat: Make screen reader spell order ids

---

src/elm/Ui/ScreenReaderText.elm

Using comma for spelling of words worked great until two or more numbers
were adjacent in the text, then the screen reader read "seven comma
seven". Now changed to using space, which the screen reader reads
correctly, although a little faster than when using comma.

fix: Spell words by using space

---

src/elm/Ui/ScreenReaderText.elm

When copying the visible text, the last letter from the spellable screen
reader only text was also included as it were no seperators (like comma)
between the screen reader only text and the visible text.

fix: Remove spellable text copy bug

---

e2e-tests/cypress/support/commands.js
src/elm/Page/Shop/Carnet.elm
src/elm/Page/Shop/CommonViews.elm
src/elm/Page/Shop/Period.elm
src/elm/Page/Shop/Summary.elm
src/elm/Ui/Input/Radio.elm
src/elm/Ui/ScreenReaderText.elm
src/static/styles/ui.scss

Made the hidden original radio button input not selectable for screen
reader cursor, making the label not be read twice.
Also removed required Bool parameter for radio onCheck event, as it was
uneccesary since a radio button may never be unchecked.
Added an optional aria label which may be passed to a radio button.

feat: Improve radio buttons accessibility

---

src/elm/Ui/ProgressHeader.elm

The progressbar role is meant for time consuming tasks the user has to
wait for, not for progressing through a series of manual steps. Instead
describe the progress bar as a figure with its own aria label.

feat: Use figure instead of progressbar role

---

src/elm/Ui/GlobalNotifications.elm

When there was no notifications, the parent div was still present with
its paddings. This parent div blocked half the header, making the header
logo and hamburger button hard to click on mobile. This was especially
present on older Android versions, where the hamburger menu was almost
impossible to click.

feat: Remove empty notifications div

---

src/elm/Ui/Input/EditSection.elm
src/static/styles/ui.scss

When the edit button was placed under the text content of the edit
section, the destructive group was placed even further down, even
though the edit button was not visible. This looked strange,
especially on mobile devices.

feat: Remove edit button when editing EditSection

---

src/elm/Ui/Message.elm

Valid messages are most often used as global notifications when a
action was completed successfully. These announcements should be
announced to users using screen readers.

feat: Polite announcement of valid messages

---

src/elm/Ui/AccessibleFieldset.elm
src/elm/Ui/Group.elm
src/elm/Ui/Input/Radio.elm
src/static/styles/ui.scss

The group section was a h3 header with a button as the child element.
This was not handled well by all screen readers, where some were
confused if the focused item was a header or a button. Changed the group
sections to only be buttons, and not headers.
Also some other small improvements regarding hidden fieldset legends not
being focusable by screen reader, and including the radio button
subtitle in its aria label.

feat: Screen reader improvements for Group expandables

---

.gitignore

Tidligere har `.gitignore` inneholdt en kombinasjon av ignorerte filer og tillatte filer, noe som kanskje ikke er så lesbart, og samtidig har medført at f.eks. `src/static/index.html` og `src/static/index.js` kun ble tracket siden de eksisterte før `.gitignore` sist ble endret.
Denne PR-en gjør at `.gitignore` kun inneholder de filer og mapper som faktisk skal ignoreres, noe som gjerne er mer intuitivt.

Mer intuitiv .gitignore for static-filer

---

src/static/index.html
src/static/index.js
webpack.config.js

Sidetittelen på nettbutikken har tidligere vært hardkodet til AtB Nettbutikk i `index.html`, og fra og med nylig blitt dynamisk overskrevet gjennom i Elm. Denne løsningen har sørget for en liten forsinkelse før sidetittelen blir overskrevet og brukere i f.eks. Nordland kunne derfor oppleve at sidetittel er `AtB Nettbutikk` et lite sekund før tittelen blir `Reis Nettbutikk.`
Dette blir nå ordnet gjennom at mulige sidetitler finnes i `webpack.config.js` og resolves basert på orgId som er gitt til webpack.

Dynamisk setting av siteTitle i index.html

---

cloudbuild.yaml

Det ligger en cloudbuild.yml fil brakk fra tidligere CI løsninger her, men egentlig så er det nyttig å ha en som er oppdatert. Slik kan f.eks NFK rulle ut enkelt i staging og prod basert på branches og bruke AtBs via GH Action på PR, så det kan gjøre regresjonstester der og.
Nå har jeg tatt utgangspunkt i guide fra https://cloud.google.com/build/docs/deploying-builds/deploy-firebase
Der setter det opp tilganger til Firebase via IAM, men jeg har også sett tidligere eksempler og som vari cloudbuild her fra før der det blir generert opp en kryptert token som manuelt settes inn. Jeg kunne ikke finne en umiddelbar måte å støtte flere miljøer med bruk av krypterte secrets, og eksempler jeg fant viste til flere yaml-filer. Det syns jeg blir en lite skalerbar løsning. Så forslaget er å følge det …

chore: updates cloud build to use env vars

---

src/static/index.html

Det er en "feil" med måten title blir injected på her. Det blir satt uten anførselstegn. Det er teknisk sett OK uten XHTML strict mode, men det er sårbart ut i fra hva innholdet til title kan være. Burde være anførselstegn rundt verdien.

fix: html meta syntax for title injection from lodash templates

---

.github/workflows/e2e-tests-firefox.yml
e2e-tests/cypress.json
e2e-tests/cypress/integration/pageobjects/myprofile.pageobject.js
e2e-tests/cypress/integration/pageobjects/onboarding.pageobject.js
e2e-tests/cypress/integration/tests/carnettickets.e2e_spec.js
e2e-tests/cypress/integration/tests/missing_storedInformation.e2e_spec.js
e2e-tests/cypress/integration/tests/myprofile.e2e_spec.js
e2e-tests/cypress/integration/tests/mytickets.e2e_spec.js
e2e-tests/cypress/integration/tests/periodtickets.e2e_spec.js
e2e-tests/cypress/integration/tests/x_onboarding.e2e_spec.js
e2e-tests/cypress/support/commands.js
e2e-tests/package.json
e2e-tests/yarn.lock

Updates to the e2e-tests:
- Globally removed a11y-checks for "image-alt" (#406)
- Updated dates on future ticket (current future ticket is soon to be active)
- New paths for paymentcard icons
- New docker-image for firefox-tests

test: e2e-fixes

---

orgs/atb.json
orgs/nfk.json
src/elm/Base.elm
src/elm/Data/Organization.elm
src/elm/Main.elm
src/elm/Page/Login.elm

Denne PR sørger for at de nederste linkene på Login-skjerm er dynamiske basert på OOS-organisasjon. (orgId)
Dersom feltene ikke finnes i `<org>.json`-filen, vises heller ikke linkteksten for det manglende feltet i nettbutikken for gitt orgId.
Teksten på den øverste linken er også endret fra "Les mer om AtBs nye reisetjenester" til "Les mer om **våre** nye reisetjenester" for å kunne fungere utenfor AtB-kontekst.
Vises slik med orgId satt til nfk:

Dynamiske lenker for oversettelser og intro til nye reisetjenester

---

src/elm/Page/Account.elm

Lukker #427 
Lagt på target _blank og lagt til i lenketeksten at erklæringen åpnes i ny fane. Fremdeles dynamisk url etter orgId.

Åpne personvernserklæring i ny fane

---

src/elm/Page/Onboarding.elm

When creating an email account, if the user typed a phone number in the
"Profilinformasjon"-screen and then selected "Hopp over", the phone
number was sent to the server. This is not the wanted behaviour, as
choosing "Hopp over" should not send any filled values.

fix: Not send email/phone when skipping onboarding

---

orgs/atb.json
orgs/nfk.json
src/elm/Base.elm
src/elm/Data/Organization.elm
src/elm/Main.elm
src/elm/Page/Login.elm

Lenken som heter `"Vi oppgraderer"` peker til AtB Beta sine sider, men burde være dynamisk for hver organisasjon som tar i bruk nettbutikken. Derfor er lenka gjort dynamisk basert på `orgId`, og hvis feltet i `<org>.json` ikke eksisterer, fjernes lenken, men meldingen ellers består.
Har også lagt til rette for separate URLer for ny nettbutikk (`newWebshopUrl`) og ny app, foreløpig brukes kun ny nettbutikk.

Dynamisk URL i prerequisites popup

---

src/static/index.js

Configuration that does not need to be configured based on os, app
version, invitation codes, etc., does not need to be in Remote Config.
They are now moved to Firestore which has the benefit of being updated
instantly in webshop and app when changed in Firestore.

feat: Load configuration from FireStore

---

src/elm/Page/Overview.elm
src/elm/Page/Shop/Period.elm
src/elm/Ui/TicketDetails.elm
src/elm/Util/FareContract.elm

The website showed warning that the user had existing overlapping ticket
when the existing carnet has no tickets left. The reason for this was
that just the valid from and valid to fields were checked on carnet.

fix: No overlapping ticket warning if empty carnet

---

src/elm/Page/Overview.elm
src/elm/Ui/TicketDetails.elm
src/elm/Util/FareContract.elm

In the overview-screen, show fare contracts which has a future valid
from date. This was unintentionally changed in a previous issue.

fix: Show fare contracts with future valid from

---

orgs/nfk.json

Erstatter NFK sin link til info om oppgradering av nettbutikk. Referanse: https://jira.bouvet.no/browse/NLFKRDP-99

fix: replace nfk webshop upgrade url

---

src/static/styles/main.scss
src/static/styles/ui.scss

Med overgang til mer dynamisk bilder som støtter ulike bilder for darkmode osv, så er det enkelte steder hvor det ikke blir hensyntatt i spacing. Dette er et forsøk på å fikse det.

fix: handle spacing for every potential ui-icon components

---

src/elm/Util/PhoneNumber.elm

Som diskutert på [Slack](https://mittatb.slack.com/archives/C025NUF4WA0/p1639046753159800) er det en bug som gjør at "+47" blir sendt inn som telefonnummer, dersom man f.eks. bruker tab for å klikke seg gjennom onboardingen etter å ha autentisert med e-post. Dette har deretter ført til at onboardingen feiler med melding "Ukjent feil".
Denne PR fjerner +47 før requesten mot `/register` blir sendt inn til Firebase, dersom kun prefiks og ikke nummer finnes i input.

fix: Avoid posting "+47" as phone number on register

---

src/elm/Page/Onboarding.elm

They were marked as required in the HTML, but was not actually required.

feat: Onboarding fields not required

---

webpack.config.js

Virker som webpack her setter opp noe proxy-filer for routing som ikke blir håndtert rett. Men etter nærmere ettertanke så tenker jeg at det er vel ingen grunn til å ha url eller file loading på data fra css/scss her. Dette unngår å gjøre noen ekstra kode for håndtering av svgs fra css og fikser feil med ikke lastet bakgrunnsbilde nå i staging og prod.

fix: svg loading from css files

---

src/elm/Environment.elm
src/elm/Main.elm
src/elm/Page/Account.elm
src/elm/Page/Overview.elm
src/static/index.js
src/static/styles/main.scss

Jf. tidligere feature rundt visning av customer number (#469), gjorde jeg på en måte en liten blunder men som egentlig er en fordel: Jeg tok ikke høyde for at customer number ikke kunne eksistere. Dette for at vi egentlig skal kunne ha customer number uansett ved innlogging. Men jeg glemte å ta høyde for tilfeller hvor registrering av bruker har feilet.
Historisk sett har skjedd litt pga ymse årsaker og det har vært vanskelig å fange opp. Det er egentlig ikke noe som skal skje, men det kan skje en gang i jubelåret og da ønsker vi at kunden tar kontakt. Forslaget mitt er en enkel melding som viser det her:
Vi kan velge å gjøre mer ut av det med større varsel osv, men dette er egentlig en edge case (som har vist seg å ha skjedd noen ganger).

feat: handle cases where there are no customer number set on profile

---

orgs/atb.json
orgs/nfk.json
src/elm/Base.elm
src/elm/Data/Organization.elm
src/elm/Main.elm
src/elm/Page/Account.elm

Flytter ut URL til org-conf-filer. Enklere å endre og se hva som kan endres. Gjør det også mulig for andre orgs å overstyre.

feat: makes buy travel card url configurable

---

package.json
webpack.config.js
yarn.lock

Nå er det lagt inn en autogenerering av en Service Worker som traverserer alle static assets og prefetcher de. Fordelen er at dersom du kommer over et bilde så vil det ikke være et midlertidig øyeblikk hvor bildet lastes (i de fleste tilfeller).
Ulempen her er at vi har ingen god måte å vite hvilke bilder som er i bruk eller ikke (uten å manuelt vedlikeholde det). Tradisjonelt sett kan dette gjøres med å bruke webpack og loading av filer via deres modulsystem som gjør at du vet hvilke filer som skal flyttes over. Her via Elm så er det ikke noe støtte for importing og generering av relative paths for bruk av bilder til img-tags. Dvs at vi bare refererer løst til filer som ligger i en mappe.
Tidligere betydde det noen ekstra bilder som ble lastet inn som brukeren egentlig ikke hadde behov …

chore: remove workbox and sw generation

---

src/elm/Page/Shop/Period.elm

Dersom det bare er ett periodeprodukt gir det mening å ikke gi brukeren valg om å endre. Spesielt nyttig i tilfeller hvor man vil feature toggle inn og ut produkter.

feat: makes ticket type readonly on period if only one ticket

---

src/elm/Data/Reservation.elm
src/elm/Data/Ticket.elm
src/elm/Main.elm
src/elm/Page/Overview.elm
src/elm/Page/Shop/Carnet.elm
src/elm/Page/Shop/Period.elm
src/elm/Page/Shop/Summary.elm
src/elm/Service/Misc.elm
src/elm/Service/Ticket.elm
src/elm/Ui/TicketDetails.elm
src/elm/Util/FareContract.elm
src/elm/Util/Reservation.elm
src/static/index.js

breaking-change: Requires update-reservation Cloud Function, new ticketing service.
- Updates Webshop to send in sca_excemption when not Vipps payment
- Changes to use reservation stored in Firebase Store instead of locally in memory. Currently not taking full advantage of that except it is persistent between instances (app/webshop) and persistent when refreshing site. A good follow-up of this task is to better handle cancellation/timeouts etc and utilize reservation persistence more.
- Adds payment type to the reservation as this has been an expressed wish previously but not available in the data before.
---

breaking-change: flag for sca excemption to reserve

---

e2e-tests/cypress/integration/pageobjects/buyticket.pageobject.js
e2e-tests/cypress/integration/tests/periodtickets.e2e_spec.js

Pga testing av nye billettprodukter så er det lagt til flere billettyper i staging, hvor 24-timersbilletten er satt som default per nå. Hvorvidt denne skal være default er usikkert, men endrer e2e-testene så de kjører fint.

fix: e2e - make 24hr default ticket for tests to pass

---

src/elm/Service/Ticket.elm

The SCA exemption flow is not working as intented when paying with
MasterCard in production.

fix: Not sca_exemption if payment type MasterCard

---

src/static/index.js

Closes #502 
The problem is that due to `securityLevel` existing as a field, `doc.data()` will not be `undefined` or an empty object, and the onboarding will thus never start. As far as I can tell, `id` as a field is only added once onboarding has been completed, so we check that that field is set to a non-falsey value.

Trigger onboarding if profile document doesn't have an id

---

e2e-tests/cypress.json
e2e-tests/cypress/integration/tests/a11y.e2e_spec.js
e2e-tests/cypress/integration/tests/carnettickets.e2e_spec.js
e2e-tests/cypress/integration/tests/missing_storedInformation.e2e_spec.js
e2e-tests/cypress/integration/tests/mytickets.e2e_spec.js
e2e-tests/cypress/integration/tests/periodtickets.e2e_spec.js

Carnet tickets have temporarily been removed from staging by Entur. These tests should therefor be disabled until the product is back.
The tests are verifying a ticket that starts in the future. That future is now, so a new ticket for the future is added.

test: e2e tests fix
